import type { Metadata } from "next";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { ThemeProvider } from "@/components/theme-provider";
import { getCurrentRole } from "@/lib/current-role";
import { UserRole } from "@prisma/client";
import { UserButton } from "@/components/auth/user-button";
import { FormError } from "@/components/form-error";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role = await getCurrentRole();

  if (role && role !== UserRole.ADMIN) {
    return (
      <div className="w-screen h-screen flex justify-center items-center flex-col gap-2">
        <UserButton />
        <FormError message="go away hacker!" />

        <FormError message="you are not allowed in this place" />
      </div>
    );
  }

  return (
    <EdgeStoreProvider>
      <div>{children}</div>
    </EdgeStoreProvider>
  );
}
